# encoding: utf-8
# Generates regex/unicode_tables.mbt from the running Ruby's Onigmo property definitions,
# so that \p{Alpha} etc. agree exactly with the oracle Ruby. Also emits the simple
# case-folding orbits Onigmo uses for /i (single code point equivalences only).
props = {
  'alpha' => /\p{Alpha}/, 'alnum' => /\p{Alnum}/, 'word' => /\p{Word}/, 'blank' => /\p{Blank}/,
  'space' => /\p{Space}/, 'upper' => /\p{Upper}/, 'lower' => /\p{Lower}/, 'digit' => /\p{Digit}/,
  'punct' => /\p{Punct}/, 'letter' => /\p{L}/, 'lu' => /\p{Lu}/, 'll' => /\p{Ll}/,
}
scalars = (0...0x110000).reject { |cp| (0xD800..0xDFFF).cover?(cp) }
out = +"// Code generated by scripts/gen_unicode_tables.rb from Ruby #{RUBY_VERSION} (Unicode #{RbConfig::CONFIG['UNICODE_VERSION']}). DO NOT EDIT.\n"
props.each do |name, rx|
  ranges = []
  start = nil
  (0..0x110000).each do |cp|
    inside = cp < 0x110000 && !(0xD800..0xDFFF).cover?(cp) && rx.match?([cp].pack('U'))
    if inside
      start ||= cp
    elsif start
      ranges << start << cp - 1
      start = nil
    end
  end
  label = { 'letter' => 'L', 'lu' => 'Lu', 'll' => 'Ll' }[name] || name.capitalize
  out << "\n///|\n/// Inclusive code point ranges (flattened lo/hi pairs) for `\\p{#{label}}`.\nlet #{name}_ranges : FixedArray[Int] = [\n"
  ranges.each_slice(8) { |s| out << '  ' << s.map { |v| format('0x%X', v) }.join(', ') << ",\n" }
  out << "]\n"
end

# Case-insensitive equivalence classes: candidates come from the case mappings,
# each edge is confirmed with Onigmo itself, and classes are closed with union-find.
parent = {}
find = lambda do |x|
  parent[x] = x unless parent.key?(x)
  parent[x] = find.(parent[x]) if parent[x] != x
  parent[x]
end
same_ci = lambda do |a, b|
  Regexp.new("\\A#{Regexp.escape(a)}\\z", Regexp::IGNORECASE).match?(b) &&
    Regexp.new("\\A#{Regexp.escape(b)}\\z", Regexp::IGNORECASE).match?(a)
end
scalars.each do |cp|
  s = [cp].pack('U')
  cands = [s.downcase, s.upcase, s.swapcase, s.capitalize, s.downcase(:fold)].uniq
  cands.each do |t|
    next if t == s || t.length != 1
    next unless same_ci.(s, t)
    a = find.(cp)
    b = find.(t.ord)
    parent[a] = b if a != b
  end
end
orbits = Hash.new { |h, k| h[k] = [] }
parent.keys.each { |cp| orbits[find.(cp)] << cp }
nxt = {}
orbits.each_value do |members|
  members.sort!
  next if members.size < 2
  members.combination(2).each do |a, b|
    warn "not equivalent under /i: U+#{a.to_s(16)} U+#{b.to_s(16)}" unless same_ci.([a].pack('U'), [b].pack('U'))
  end
  members.each_with_index { |m, i| nxt[m] = members[(i + 1) % members.size] }
end
keys = nxt.keys.sort
out << "\n///|\n/// Code points with a non-trivial case-insensitive equivalence class (sorted).\nlet fold_keys : FixedArray[Int] = [\n"
keys.each_slice(8) { |s| out << '  ' << s.map { |v| format('0x%X', v) }.join(', ') << ",\n" }
out << "]\n"
out << "\n///|\n/// `fold_next[i]` is the next member of `fold_keys[i]`'s equivalence class (cyclic).\nlet fold_next : FixedArray[Int] = [\n"
keys.each_slice(8) { |s| out << '  ' << s.map { |v| format('0x%X', nxt[v]) }.join(', ') << ",\n" }
out << "]\n"
File.write File.expand_path('../regex/unicode_tables.mbt', __dir__), out
