# encoding: utf-8
# Generates core/rx.mbt from the regexp constants of the Ruby implementation
# (resolved, so interpolated character classes are expanded exactly).
$LOAD_PATH.unshift File.expand_path('../.repos/asciidoctor/lib', __dir__)
require 'asciidoctor'
def snake(name)
  name.gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2').gsub(/([a-z\d])([A-Z])/, '\1_\2').downcase
end
def lit(s)
  '"' + s.gsub('\\') { '\\\\' }.gsub('"') { '\\"' }.gsub("\n") { '\\n' }.gsub("\t") { '\\t' } + '"'
end
def rx(r)
  flags = (r.options & Regexp::MULTILINE) != 0 ? ', flags="m"' : ''
  "@regex.re(#{lit r.source}#{flags})"
end
out = +"// Code generated by scripts/gen_rx.rb from lib/asciidoctor/*.rb. DO NOT EDIT.\n"
emitted = {}
[[Asciidoctor, ''], [Asciidoctor::Substitutors, ''], [Asciidoctor::Parser, ''], [Asciidoctor::AttributeList, 'attribute_list_'], [Asciidoctor::PathResolver, 'path_resolver_']].each do |mod, prefix|
  mod.constants(false).sort.each do |c|
    v = mod.const_get c
    name = prefix + snake(c.to_s)
    next if emitted[name]
    if Regexp === v
      emitted[name] = true
      out << "\n///|\nlet #{name} : @regex.Regex = #{rx v}\n"
    elsif Hash === v && !v.empty? && v.values.all? { |x| Regexp === x }
      emitted[name] = true
      out << "\n///|\nlet #{name} : Map[String, @regex.Regex] = {\n"
      v.each { |k, r| out << "  #{lit k.to_s}: #{rx r},\n" }
      out << "}\n"
    end
  end
end
{ 'quote_subs_normal' => Asciidoctor::QUOTE_SUBS[false], 'quote_subs_compat' => Asciidoctor::QUOTE_SUBS[true] }.each do |name, subs|
  out << "\n///|\nlet #{name} : Array[(String, String, @regex.Regex)] = [\n"
  subs.each { |type, scope, r| out << "  (#{lit type.to_s}, #{lit scope.to_s}, #{rx r}),\n" }
  out << "]\n"
end
out << "\n///|\nlet replacements : Array[(@regex.Regex, String, String)] = [\n"
Asciidoctor::REPLACEMENTS.each { |r, repl, rest| out << "  (#{rx r}, #{lit repl}, #{lit rest.to_s}),\n" }
out << "]\n"
Asciidoctor::InlinePassRx.each do |k, (a, b, r)|
  out << "\n///|\nlet inline_pass_rx_#{k} : (String, String?, @regex.Regex) = (#{lit a}, #{b ? "Some(#{lit b})" : "None"}, #{rx r})\n"
end
File.write File.expand_path('../core/rx.mbt', __dir__), out
puts emitted.size
