# encoding: utf-8
# Generates regex/unicode_tables.mbt from the running Ruby's Onigmo property definitions,
# so that \p{Alpha} etc. agree exactly with the oracle Ruby.
props = { 'alpha' => /\p{Alpha}/, 'alnum' => /\p{Alnum}/, 'word' => /\p{Word}/, 'blank' => /\p{Blank}/, 'space' => /\p{Space}/ }
out = +"// Code generated by scripts/gen_unicode_tables.rb from Ruby #{RUBY_VERSION} (Unicode #{RbConfig::CONFIG['UNICODE_VERSION']}). DO NOT EDIT.\n"
props.each do |name, rx|
  ranges = []
  start = nil
  (0..0x110000).each do |cp|
    inside = cp < 0x110000 && !(0xD800..0xDFFF).cover?(cp) && rx.match?([cp].pack('U'))
    if inside
      start ||= cp
    elsif start
      ranges << start << cp - 1
      start = nil
    end
  end
  out << "\n///|\n/// Inclusive code point ranges (flattened lo/hi pairs) for `\\p{#{name.capitalize}}`.\nlet #{name}_ranges : FixedArray[Int] = [\n"
  ranges.each_slice(8) { |s| out << '  ' << s.map { |v| format('0x%X', v) }.join(', ') << ",\n" }
  out << "]\n"
end
File.write File.expand_path('../regex/unicode_tables.mbt', __dir__), out
