# encoding: utf-8
# Generates internal/rb/case_tables.mbt: Ruby's full Unicode downcase/upcase mappings
# for non-ASCII code points (ASCII is handled inline), and the titlecase mappings
# `capitalize` uses for a first character where they differ from upcase.
def esc(s)
  s.each_char.map { |c| o = c.ord; o < 0x20 || o > 0x7e ? format('\\u{%x}', o) : (c == '"' || c == '\\' ? "\\#{c}" : c) }.join
end
out = +"// Code generated by scripts/gen_case_tables.rb from Ruby #{RUBY_VERSION} (Unicode #{RbConfig::CONFIG['UNICODE_VERSION']}). DO NOT EDIT.\n"
{ 'lower' => :downcase, 'upper' => :upcase }.each do |name, meth|
  cps = []
  maps = []
  (0x80..0x10FFFF).each do |cp|
    next if (0xD800..0xDFFF).cover?(cp)
    s = [cp].pack('U')
    m = s.send(meth)
    next if m == s
    cps << cp
    maps << m
  end
  out << "\n///|\nlet #{name}_keys : FixedArray[Int] = [\n"
  cps.each_slice(10) { |sl| out << '  ' << sl.map { |v| format('0x%X', v) }.join(', ') << ",\n" }
  out << "]\n\n///|\nlet #{name}_vals : FixedArray[String] = [\n"
  maps.each_slice(8) { |sl| out << '  ' << sl.map { |v| %("#{esc v}") }.join(', ') << ",\n" }
  out << "]\n"
end
# titlecase (String#capitalize of one character) where it differs from upcase
cps = []
maps = []
(0x80..0x10FFFF).each do |cp|
  next if (0xD800..0xDFFF).cover?(cp)
  s = [cp].pack('U')
  t = s.capitalize
  next if t == s.upcase
  cps << cp
  maps << t
end
out << "\n///|\nlet title_keys : FixedArray[Int] = [\n"
cps.each_slice(10) { |sl| out << '  ' << sl.map { |v| format('0x%X', v) }.join(', ') << ",\n" }
out << "]\n\n///|\nlet title_vals : FixedArray[String] = [\n"
maps.each_slice(8) { |sl| out << '  ' << sl.map { |v| %("#{esc v}") }.join(', ') << ",\n" }
out << "]\n"
File.write File.expand_path('../internal/rb/case_tables.mbt', __dir__), out
