# encoding: utf-8
# Differential oracle for the regex engine: runs each Asciidoctor regex (from
# tests/regex/regexes.json) with Ruby over a corpus of AsciiDoc lines/paragraphs and
# writes regex/oracle_test.mbt with expected capture offsets (in UTF-16 code units).
require 'json'
ROOT = File.expand_path '..', __dir__
UP = File.join ROOT, '.repos/asciidoctor'
regexes = JSON.parse File.read(File.join(ROOT, 'tests/regex/regexes.json'))
lines = []
paras = []
(Dir[File.join(UP, 'docs/**/*.adoc')] + Dir[File.join(UP, 'test/*.rb')] + Dir[File.join(UP, 'test/fixtures/*.adoc')]).sort.each do |f|
  text = File.read(f, encoding: 'UTF-8').scrub
  text.each_line { |l| lines << l.chomp }
  text.split(/\n{2,}/).each { |p| paras << p if p.lines.size > 1 && p.size < 600 }
end
lines.uniq!
paras.uniq!
extra = ["Doc Writer <doc@example.com>", "Mary_Sue Brontë", "v1.0, 2013-01-01: Ring in the new year release", "é *bold* é", "日本語 _強調_ テキスト", "emoji 😀 *x* 😀", "a b", "[[idname,Reference Text]]", "{counter:foo}", "\\{escaped}", "**", "*a*", "``", "`a`b", "tag::x[]", "a\n", "a\n\n", "", "\n"]
lines.concat extra
def u16(str, byte_idx_char)
  # convert Ruby char index to UTF-16 index
  str[0, byte_idx_char].encode('UTF-16LE').bytesize / 2
end
def offsets(m, str)
  (0...m.size).flat_map { |i| b = m.begin(i); b ? [u16(str, b), u16(str, m.end(i))] : [-1, -1] }
end
def esc(s)
  out = +'"'
  s.each_char do |c|
    case c
    when '"' then out << '\\"'
    when '\\' then out << '\\\\'
    when "\n" then out << '\\n'
    when "\r" then out << '\\r'
    when "\t" then out << '\\t'
    else
      o = c.ord
      if o < 0x20 || o == 0x7f then out << format('\\u{%x}', o)
      else out << c end
    end
  end
  out << '"'
end
cases = []
seen = {}
regexes.each do |r|
  next if r['interpolated']
  src = r['source']
  multi = r['options'] ? (r['options'] & 4 != 0) : r['flags'].to_s.include?('m')
  next if seen[[src, multi]]
  seen[[src, multi]] = true
  rx = begin
    Regexp.new(src, multi ? Regexp::MULTILINE : 0)
  rescue StandardError
    next
  end
  corpus = multi ? (paras + lines) : lines
  hits = []
  misses = []
  corpus.each do |s|
    m = rx.match s
    if m
      if hits.size < 40
        all = []
        pos = 0
        s.scan(rx) { all.concat offsets($~, s); all << -2 }
        hits << [s, offsets(m, s), all]
      end
    elsif misses.size < 8
      misses << [s, nil, []]
    end
    break if hits.size >= 40 && misses.size >= 8
  end
  (hits + misses).each { |s, o, a| cases << [src, multi ? 'm' : '', s, o, a] }
  # seeded random inputs built from the pattern's punctuation plus word chars,
  # whitespace, newlines and non-ASCII characters
  rng = Random.new(src.hash & 0xffffffff)
  alphabet = (src.scan(/[^\w\s\\]/).uniq + %w(a b Z 9 _ é 😀) + [' ', ' ', "\t", "\n", 'x', 'y']).uniq
  20.times do
    str = Array.new(rng.rand(0..24)) { alphabet[rng.rand(alphabet.size)] }.join
    m = rx.match str
    all = []
    str.scan(rx) { all.concat offsets($~, str); all << -2 }
    cases << [src, multi ? 'm' : '', str, m && offsets(m, str), all]
  end
end
File.open(File.join(ROOT, 'regex/oracle_test.mbt'), 'w') do |f|
  f.puts "// Code generated by scripts/gen_regex_oracle.rb (Ruby #{RUBY_VERSION}). DO NOT EDIT."
  f.puts
  chunks = cases.each_slice(400).to_a
  chunks.each_with_index do |chunk, ci|
    f.puts "///|"
    f.puts "fn oracle_chunk_#{ci}() -> Array[(String, String, String, Array[Int]?, Array[Int])] {"
    f.puts "  ["
    chunk.each do |src, fl, s, o, a|
      f.puts "    (#{esc src}, #{esc fl}, #{esc s}, #{o ? "Some([#{o.join(', ')}])" : 'None'}, [#{a.join(', ')}]),"
    end
    f.puts "  ]"
    f.puts "}"
    f.puts
  end
  f.puts "///|"
  f.puts "fn oracle_cases() -> Array[(String, String, String, Array[Int]?, Array[Int])] {"
  f.puts "  [#{chunks.each_index.map { |ci| "..oracle_chunk_#{ci}()" }.join(', ')}]"
  f.puts "}"
  f.puts <<~MBT

    ///|
    test "regex oracle: agrees with Ruby on Asciidoctor patterns" {
      let failures = []
      let mut last_src = ""
      let mut last_re : @regex.Regex? = None
      let oracle_cases = oracle_cases()
      for c in oracle_cases {
        let (src, flags, input, expected, expected_all) = c
        if src != last_src {
          last_src = src
          last_re = Some(@regex.compile(src, flags~))
        }
        guard! last_re is Some(re)
        let actual = match re.find(input) {
          Some(m) => Some(Array::makei(m.size() * 2, i => if i % 2 == 0 { m.begin(i=i / 2) } else { m.end(i=i / 2) }))
          None => None
        }
        let all = []
        for m in re.find_all(input) {
          for i in 0..<m.size() {
            all.push(m.begin(i~))
            all.push(m.end(i~))
          }
          all.push(-2)
        }
        if all != expected_all {
          failures.push("scan /\\{src}/\\{flags} on \\{input.escape()}: expected \\{Repr(expected_all)}, got \\{Repr(all)}")
        }
        if actual != expected {
          failures.push("/\\{src}/\\{flags} on \\{input.escape()}: expected \\{Repr(expected)}, got \\{Repr(actual)}")
        }
      }
      let hits = oracle_cases.filter(c => c.3 is Some(_)).length()
      assert_true(hits > 1000)
      if failures.length() > 0 {
        fail("\\{failures.length()} / \\{oracle_cases.length()} failures:\\n" + failures[:@cmp.minimum(40, failures.length())].join("\\n"))
      }
    }
  MBT
end
puts "#{cases.size} cases"
