# Generates core/stylesheet_data.mbt from data/stylesheets/asciidoctor-default.css.
css = File.read(File.expand_path('../.repos/asciidoctor/data/stylesheets/asciidoctor-default.css', __dir__), mode: 'rb:UTF-8').rstrip
out = +"// Code generated by scripts/gen_stylesheet.rb. DO NOT EDIT.\n\n///|\n/// The default Asciidoctor stylesheet (asciidoctor-default.css).\npub let primary_stylesheet_data : String =\n"
css.each_line { |l| out << "  #|" << l.chomp << "\n" }
File.write File.expand_path('../core/stylesheet_data.mbt', __dir__), out
